### PR TITLE
Minor update to README.

### PR DESCRIPTION
**Pull request by commoddity**
To point to the current API gateway repo and a few other small tweaks for clarity, as well as update to the .env.template file (default repo pathnames for the other repos).

One question before PR can be merged. The README.md file states:

```Then, make sure you add the blockchains you are concerned with to the `Blockchains` collection and you have added them to the chains.json in `config/chains.json` in this project.```

Currently the only `chains.json` file in the repo is located at `pocket-e2e-stack/stacks/pokt-net/shared/chains.json`. Just wanting to confirm if that is the correct file that the readme should be pointing to. If so, I'll update the file before the PR should be merged.

### CODE REVIEW

**Review by crisog — APPROVED** [review]
About time 🚀

**Comment by nymd** [comment]
I think the instructions are implying you need to create your own chains.json as that file you linked doesn't look correct. @crisog?

**Comment by crisog** [comment]
> I think the instructions are implying you need to create your own chains.json as that file you linked doesn't look correct. @crisog?

In my experience, you can leave the `chains.json` file as-is. You only need to make sure to use it while creating transaction, or interacting with the localnet in general.

**Comment by crisog** [comment]
This is the use I've made of it, not quite sure how it can impact other things as this is uniquely intended to test locally.

**Comment by commoddity** [comment]
Gotcha. I just found that part a bit confusing since neither the `config` folder nor the `chains.json` file that bit is referencing exist in the repo by default.

**Pull request merged**
